version: "3"
services:
  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    ports:
      - "9001:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://my_postgres:5432/sonarqube
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    depends_on:
      - postgres
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions

  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      - POSTGRES_DB=sonarqube  
      - POSTGRES_USER=sonar  
      - POSTGRES_PASSWORD=sonar 
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  sonarqube_data:
    external: true
  sonarqube_logs:
    external: true
  sonarqube_extensions:
    external: true
  postgres_data:
    external: false